# Generated by Django 4.0.3 on 2022-04-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Cosmetics',
        ),
    ]
