# Generated by Django 4.0.3 on 2022-04-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_rename_ingredients_cosmetics'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetics',
            name='inci',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
